services:
  api: 
    build:
     context: ../app/api

    networks:
    - private
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY:  ${MINIO_USER}
      MINIO_BUCKET: resumes

    ports:
    - 127.0.0.1:5000:5000
    depends_on:
      - postgres
      - redis
      - minio

  web: 
    build: 
     context: ../app/web

    ports:
      - 5173:5173

    depends_on:
      - postgres

  # ai-worker:
  #   build:
  #     context: ../app/ai-worker
    
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: ${DB_PORT}
  #     DB_USER: ${POSTGRES_USER}
  #     DB_PASSWORD: ${POSTGRES_PASSWORD}
  #     DB_NAME: ${POSTGRES_DB}
  #     MINIO_ENDPOINT: minio:9000
  #     MINIO_ACCESS_KEY: ${MINIO_USER}
  #     MINIO_BUCKET: resumes


    # networks:
    #   - private

    # depends_on:
    #   - postgres
    #   - redis
    #   - minio
    

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
       - "127.0.0.1:9000:9000"
       - "127.0.0.1:9001:9001"   
    volumes:
      - minio_data:/data
    networks:
      
      - private


  postgres:
    image: postgres:18

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    networks: 
     - private

    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5433:5432"
    
  redis:
    image: redis:7

    networks: 
      - private

    


networks:
  private: 
   internal: true



volumes:
  postgres_data:
  minio_data: